import type { Metadata } from "next";
import { Inter, Tomorrow } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { checkTables } from "./lib/seed";

const tommorrow = Tomorrow({weight: "300", subsets: ["latin"], variable: "--font-tommorrow"});
const revamped = localFont({src: "Revamped.woff2", variable: "--font-revamped"});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    checkTables(); 

    return (
        <html lang="en">
        <body className={`${tommorrow.variable} ${revamped.variable}`}>{children}</body>
        </html>
    );
}
